### ISSUE TITLE
Authentication failed on registration when using capitals in Email address

### ISSUE THREAD

**Issue by Hermanverschooten** [nerves-hub/nerves_hub_cli#113] opened 2019-04-10 12:28 UTC
If you try to register a new user and enter the e-mail address with capital letters, eg `Herman@verschooten.net` then you get an authentication failure after entering the local password.

**Comment by fhunleth** [comment] 2019-04-10 12:50
Wow

**Comment by fhunleth** [comment] 2019-04-10 14:56
The authentication failure is at: https://github.com/nerves-hub/nerves_hub_web/blob/ce236cc5c304910825cd1bb16bbb7ceaaad98df7/apps/nerves_hub_web_core/lib/nerves_hub_web_core/accounts.ex#L162. 

However, the problem is more general.

It looks like the solution is to normalize email addresses whenever they're received.

**Comment by fhunleth** [comment] 2019-04-11 14:01
Email addresses can now have capital letters. The fix is in the linked PR to `nerves_hub_web`. Thanks for posting the issue.

**Closed by fhunleth** 2019-04-11 14:01 UTC
